Docker - Better handling for calling external functions

diff --git a/docker/dockerbasecontainer b/docker/dockerbasecontainer
--- a/docker/dockerbasecontainer
+++ b/docker/dockerbasecontainer
@@ -4,56 +4,11 @@
 
 #Global Variables
 dockerbasecontainer_options=(
-	'ip' 'name' 'restart' 'rm' 'shell' 'start' 'status' 'stop'
+	'exists' 'ip' 'name' 'restart' 'rm' 'shell' 'start' 'status' 'stop'
 )
 dockerbasecontainer_options_exec=('exec')
 
-#Functions
-array_to_string_delimited() {
-	# @description output array as a string, with delimiter as the separator
-	# @description reference: https://superuser.com/a/720157
-	# @param $1 delimiter 
-	# @param $2 array
-	# @output string output of the array, with delimiter as the separator
-
-	if [ $# -ge 2 ] ; then
-		local delimiter="$1"
-		local array=("${@:2:${#}}")
-
-		echo $(awk -v sep="$delimiter" '
-			BEGIN{
-				ORS=OFS="";
-				for(i=1;i<ARGC;i++){
-					arg=ARGV[i];
-					print arg,ARGC-i-1?sep:""
-				}
-			}' "${array[@]}")
-	else
-		echo "Usage: ${FUNCNAME[0]} delimiter array[@]"
-	fi
-}
-
-array_sorted_unique() {
-	# @description used to sort and remove duplicates from the provided array
-	# @description reference: https://superuser.com/a/720157
-	# @param $1 array
-	# @output string output of the array, sorted and without duplicates
-
-	if [ "${#@}" -gt 0 ]; then
-		printf '%s\n' "${@}" | sort -u
-	else
-		echo "Usage: ${FUNCNAME[0]} array"
-	fi
-}
-
-usage_options_formatted() {
-	# @description used to format usage options for consistency and readability
-	# @param $1 usage options array
-	# @output string output of the Usage statement, formatted
-	
-	array_to_string_delimited "|" $(array_sorted_unique "${@}")
-}
-
+#Core Function
 dockerbasecontainer() {
 	# @description used to add additional basic commands for docker
 	# @param $1 container name
@@ -73,6 +28,12 @@ dockerbasecontainer() {
 
 					return
 				fi;;
+			'exists')
+				if [ $(dockerbasecontainer status "$2" | awk 'NR > 1' | wc -l) -gt 0 ]; then
+					return 0
+				fi
+
+				return 1;;
 			'health')
 				echo $(docker inspect --format "{{.State.Health.Status }}" $2 2> /dev/null)
 				return ;;
@@ -80,7 +41,10 @@ dockerbasecontainer() {
 				echo $(docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' $2 2> /dev/null) | tr ' ' '\n'
 				return;;
 			'name')
-				echo "$2"
+				if (dockerbasecontainer exists "$2"); then
+					echo "$2"
+				fi
+				
 				return;;
 			'restart')
 				docker restart "$2"
@@ -104,13 +68,45 @@ dockerbasecontainer() {
 		esac
 	fi
 
-	echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockerbasecontainer_options[@]})} container-name"
-	echo "Usage: ${FUNCNAME[0]} $(usage_options_formatted ${dockerbasecontainer_options_exec[@]}) container-name [-d] target-command ..."
+	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${dockerbasecontainer_options[@]})) <container-name>"
+	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${dockerbasecontainer_options_exec[@]})) <container-name> [-d] <command>"
+}
+
+#External Functions
+dockerutil() {
+	# @description reference dockerutil to utilize it's functions
+	# @output None
+
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerutil"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerutil"
+		return 1
+	fi
+}
+
+verify_external_functions() {
+	# @description check if external functions can be loaded, or else exit the script
+	# @output None
+
+	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
 }
 
 #Main
 if [ "$0" = "${BASH_SOURCE}" ]; then
-	dockerbasecontainer "${@}"
+	verify_external_functions
+
+	case "$1" in
+		'dockerbasecontainer_options')
+			echo ${dockerbasecontainer_options[@]};;
+		'dockerbasecontainer_options_exec')
+			echo ${dockerbasecontainer_options_exec[@]};;
+		*)
+			dockerbasecontainer "${@}"
+	esac
 
 	exit $?
 fi
diff --git a/docker/dockercontainer b/docker/dockercontainer
--- a/docker/dockercontainer
+++ b/docker/dockercontainer
@@ -3,10 +3,9 @@
 # Wrapper for docker
 
 #Global Variables
-dockercontainer_options=('exists')
-dockercontainer_options_create=('recreate' 'run' 'start')
+dockercontainer_options=('recreate' 'run' 'start')
 
-#Functions
+#Core Function
 dockercontainer() {
 	# @description used for managing docker containers
 	# @param $1 container name
@@ -16,12 +15,6 @@ dockercontainer() {
 
 	if [ -n "$1" ] && [ -n "$2" ]; then
 		case "$1" in
-			'exists')
-				if [ $(dockerbasecontainer status "$2" | awk 'NR > 1' | wc -l) -gt 0 ]; then
-					return 0
-				fi
-
-				return 1;;
 			'recreate')
 				if (dockercontainer exists "$2"); then
 					dockerbasecontainer rm "$2"
@@ -45,7 +38,7 @@ dockercontainer() {
 				bash -c "${cmd}"
 				return;;
 			'start')
-				if (! dockercontainer exists "$2"); then
+				if (! dockerbasecontainer exists "$2"); then
 					dockercontainer run "${@:2:${#}}"
 				else
 					dockerbasecontainer "$1" "$2"
@@ -58,31 +51,60 @@ dockercontainer() {
 		esac
 	fi
 
-	echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockerbasecontainer_options[@]} ${dockercontainer_options[@]})} container-name"
-	echo "Usage: ${FUNCNAME[0]} $(usage_options_formatted ${dockerbasecontainer_options_exec[@]}) container-name [-d] target-command"
-	echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options_create[@]})} container-name docker-image target-command [other-options]"
+	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted $(dockerbasecontainer dockerbasecontainer_options))) <container-name>"
+	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted $(dockerbasecontainer dockerbasecontainer_options_exec))) <container-name> [-d] <command>"
+	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${dockercontainer_options[@]})) <container-name> <docker-image> <container-command>"
 }
 
-init_dockerbasecontainer() {
-	# @description source dockerbasecontainer to make it's functions available
+#External Functions
+dockerbasecontainer() {
+	# @description reference dockerbasecontainer to utilize it's functions
 	# @output None
 
 	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
 	local scriptpath="${repodir}/docker/dockerbasecontainer"
 
 	if [ -f "${scriptpath}" ]; then
-		. ${scriptpath}
+		${scriptpath} "$@"
 	else
 		echo "Error: Could not load dockerbasecontainer"
-		exit 1
+		return 1
 	fi
 }
 
-#Main
-init_dockerbasecontainer
+dockerutil() {
+	# @description reference dockerutil to utilize it's functions
+	# @output None
 
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerutil"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerutil"
+		return 1
+	fi
+}
+
+verify_external_functions() {
+	# @description check if external functions can be loaded, or else exit the script
+	# @output None
+
+	if !(dockerbasecontainer > /dev/null); then dockerbasecontainer; exit 1; fi
+	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
+}
+
+#Main
 if [ "$0" = "${BASH_SOURCE}" ]; then
-	dockercontainer "${@}"
+	verify_external_functions
+
+	case "$1" in
+		'dockercontainer_options')
+			echo ${dockercontainer_options[@]};;
+		*)
+			dockercontainer "${@}"
+	esac
 
 	exit $?
 fi
diff --git a/docker/templates/databases/db2express/dockerdb2express b/docker/templates/databases/db2express/dockerdb2express
--- a/docker/templates/databases/db2express/dockerdb2express
+++ b/docker/templates/databases/db2express/dockerdb2express
@@ -7,7 +7,7 @@
 # Port: 50000 (configured via -p 50000:50000)
 # DB2(LUW) URL Example: jdbc:db2://localhost:50000/database_name
 
-#Functions
+#Core Function
 dockerdb2express() {
 	# @description create a docker container for DB2 Express
 	# @param $1 available commands listed in usages
@@ -41,30 +41,75 @@ dockerdb2express() {
 				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
 		esac
 	else
-		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
-		echo "Usage: ${FUNCNAME[0]} {dbcreate|dbdrop} database-name"
+		local usage_options=(
+			$(dockerbasecontainer dockerbasecontainer_options)
+			$(dockercontainer dockercontainer_options)
+		)
+
+		echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${usage_options[@]}))"
+		echo "Usage: ${FUNCNAME[0]} (dbcreate|dbdrop) <database-name>"
 	fi
 }
 
-init_dockercontainer() {
-	# @description source dockercontainer to make it's functions available
+#External Functions
+dockerbasecontainer() {
+	# @description reference dockerbasecontainer to utilize it's functions
+	# @output None
+
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerbasecontainer"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerbasecontainer"
+		return 1
+	fi
+}
+
+dockercontainer() {
+	# @description reference dockercontainer to utilize it's functions
 	# @output None
 
 	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
 	local scriptpath="${repodir}/docker/dockercontainer"
 
 	if [ -f "${scriptpath}" ]; then
-		. ${scriptpath}
+		${scriptpath} "$@"
 	else
 		echo "Error: Could not load dockercontainer"
-		exit 1
+		return 1
 	fi
 }
 
-#Main
-init_dockercontainer
+dockerutil() {
+	# @description reference dockerutil to utilize it's functions
+	# @output None
 
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerutil"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerutil"
+		return 1
+	fi
+}
+
+verify_external_functions() {
+	# @description check if external functions can be loaded, or else exit the script
+	# @output None
+
+	if !(dockerbasecontainer > /dev/null); then dockerbasecontainer; exit 1; fi
+	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
+	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
+}
+
+#Main
 if [ "$0" = "${BASH_SOURCE}" ]; then
+	verify_external_functions
+
 	dockerdb2express "${@}"
 
 	exit $?
diff --git a/docker/templates/databases/postgresql/dockerpostgresql b/docker/templates/databases/postgresql/dockerpostgresql
--- a/docker/templates/databases/postgresql/dockerpostgresql
+++ b/docker/templates/databases/postgresql/dockerpostgresql
@@ -6,7 +6,7 @@
 # Hostname: localhost
 # Port: 5432 (configured via - p5432:5432)
 
-#Functions
+#Core Function
 dockerpostgresql() {
 	# @description create a docker container for PostgreSQL
 	# @param $1 available commands listed in usages
@@ -29,29 +29,74 @@ dockerpostgresql() {
 				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
 		esac
 	else
-		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
+		local usage_options=(
+			$(dockerbasecontainer dockerbasecontainer_options)
+			$(dockercontainer dockercontainer_options)
+		)
+
+		echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${usage_options[@]}))"
 	fi
 }
 
-init_dockercontainer() {
-	# @description source dockercontainer to make it's functions available
+#External Functions
+dockerbasecontainer() {
+	# @description reference dockerbasecontainer to utilize it's functions
+	# @output None
+
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerbasecontainer"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerbasecontainer"
+		return 1
+	fi
+}
+
+dockercontainer() {
+	# @description reference dockercontainer to utilize it's functions
 	# @output None
 
 	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
 	local scriptpath="${repodir}/docker/dockercontainer"
 
 	if [ -f "${scriptpath}" ]; then
-		. ${scriptpath}
+		${scriptpath} "$@"
 	else
 		echo "Error: Could not load dockercontainer"
-		exit 1
+		return 1
 	fi
 }
 
-#Main
-init_dockercontainer
+dockerutil() {
+	# @description reference dockerutil to utilize it's functions
+	# @output None
 
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerutil"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerutil"
+		return 1
+	fi
+}
+
+verify_external_functions() {
+	# @description check if external functions can be loaded, or else exit the script
+	# @output None
+
+	if !(dockerbasecontainer > /dev/null); then dockerbasecontainer; exit 1; fi
+	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
+	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
+}
+
+#Main
 if [ "$0" = "${BASH_SOURCE}" ]; then
+	verify_external_functions
+	
 	dockerpostgresql "${@}"
 
 	exit $?
diff --git a/docker/templates/searchindexers/elasticsearch/dockerelasticsearch b/docker/templates/searchindexers/elasticsearch/dockerelasticsearch
--- a/docker/templates/searchindexers/elasticsearch/dockerelasticsearch
+++ b/docker/templates/searchindexers/elasticsearch/dockerelasticsearch
@@ -4,7 +4,7 @@
 # Hostname: localhost
 # Port: 9200 (configured via -p 9200:9200)
 
-#Functions
+#Core Function
 dockerelasticsearch() {
 	# @description create a docker container for Elasticsearch
 	# @param $1 available commands listed in usages
@@ -27,14 +27,14 @@ dockerelasticsearch() {
 		"http.cors.allow-headers: \"X-Requested-With, Content-Type, Content-Length, X-User\""
 	)
 
-	local elasticsearch_options_delimited="$(array_to_string_delimited '\\n' "${elasticsearch_options[@]}")"
+	local elasticsearch_options_delimited="$(dockerutil array_to_string_delimited '\\n' "${elasticsearch_options[@]}")"
 
 	if [ -n "$1" ]; then
 		case "$1" in
 			'recreate'|'run'|'start')
 				local init_elastic
 
-				if [ "$1" == 'recreate' ] || (! dockercontainer 'exists' "${containername}"); then
+				if [ "$1" == 'recreate' ] || (! dockerbasecontainer 'exists' "${containername}"); then
 					init_elastic=1
 				fi
 
@@ -49,29 +49,74 @@ dockerelasticsearch() {
 				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
 		esac
 	else
-		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
+		local usage_options=(
+			$(dockerbasecontainer dockerbasecontainer_options)
+			$(dockercontainer dockercontainer_options)
+		)
+
+		echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${usage_options[@]}))"
 	fi
 }
 
-init_dockercontainer() {
-	# @description source dockercontainer to make it's functions available
+#External Functions
+dockerbasecontainer() {
+	# @description reference dockerbasecontainer to utilize it's functions
 	# @output None
-	
+
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerbasecontainer"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerbasecontainer"
+		return 1
+	fi
+}
+
+dockercontainer() {
+	# @description reference dockercontainer to utilize it's functions
+	# @output None
+
 	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
 	local scriptpath="${repodir}/docker/dockercontainer"
 
 	if [ -f "${scriptpath}" ]; then
-		. ${scriptpath}
+		${scriptpath} "$@"
 	else
 		echo "Error: Could not load dockercontainer"
-		exit 1
+		return 1
 	fi
 }
 
-#Main
-init_dockercontainer
+dockerutil() {
+	# @description reference dockerutil to utilize it's functions
+	# @output None
 
+	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
+	local scriptpath="${repodir}/docker/dockerutil"
+
+	if [ -f "${scriptpath}" ]; then
+		${scriptpath} "$@"
+	else
+		echo "Error: Could not load dockerutil"
+		return 1
+	fi
+}
+
+verify_external_functions() {
+	# @description check if external functions can be loaded, or else exit the script
+	# @output None
+
+	if !(dockerbasecontainer > /dev/null); then dockerbasecontainer; exit 1; fi
+	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
+	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
+}
+
+#Main
 if [ "$0" = "${BASH_SOURCE}" ]; then
+	verify_external_functions
+
 	dockerelasticsearch "${@}"
 
 	exit $?
